zookeeper:
  image: jplock/zookeeper
  hostname: zookeeper
  expose:
   - 2181
   - 2888 
   - 3888
  cpu_shares: 128
  mem_limit: 512M   
master:
  image: tmetsch/mesos_docker
  hostname: master
  ports:
   - 5050:5050
  links:
   - zookeeper:zookeeper
  command: ./bin/mesos-master.sh --zk=zk://zookeeper:2181/mesos --ip=0.0.0.0 --work_dir=/var/lib/mesos --quorum=1
  cpu_shares: 128
  mem_limit: 512M
marathon:
  image: tmetsch/mesos_docker
  hostname: marathon
  ports:
   - 8080:8080
  links:
   - master:master
   - zookeeper:zookeeper
  environment:
   - MESOS_NATIVE_JAVA_LIBRARY=/mesos-0.26.0/build/src/.libs/libmesos.so
  command: /marathon-0.14.0/bin/start --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon --max_tasks_per_offer 10
  cpu_shares: 128
  mem_limit: 512M
node1:
  build: .
  links:
   - master:master
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /run:/run
  command: ./bin/mesos-slave.sh --master=master:5050
  privileged: true
  cpu_shares: 128
  mem_limit: 1G
openlavamaster:
  build: .
  expose:
   - 6322/udp
   - 6322/tcp
   - 6323
   - 6324
   - 6325
  ports:
   - 9876:9876
  links:
   - master:master
  working_dir: /tmp/
  command: python mesoslava/framework.py
  cpu_shares: 128
  mem_limit: 512M

