zookeeper:
  image: jplock/zookeeper
  hostname: zookeeper
  expose:
   - 2181
   - 2888 
   - 3888
  cpu_shares: 128
  mem_limit: 512M   
master:
  image: tmetsch/mesos_docker
  hostname: master
  ports:
   - 5050:5050
  links:
   - zookeeper:zookeeper
  command: ./bin/mesos-master.sh --zk=zk://zookeeper:2181/mesos --ip=0.0.0.0 --work_dir=/var/lib/mesos --quorum=1
  cpu_shares: 128
  mem_limit: 512M
marathon:
  image: tmetsch/mesos_docker
  hostname: marathon
  ports:
   - 8080:8080
  links:
   - master:master
   - zookeeper:zookeeper
  command: /marathon-1.1.1/bin/start --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon --max_tasks_per_offer 10
  cpu_shares: 128
  mem_limit: 512M
node1:
  build: .
  links:
   - master:master
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - /run:/run
  command: ./bin/mesos-slave.sh --no-systemd_enable_support --work_dir=/var/lib/mesos --master=master:5050
  privileged: true
  cpu_shares: 128
  mem_limit: 1G
#nodedocky:
#  image: tmetsch/mesos_docker
#  links:
#   - master:master
#  volumes:
#    - /sys/fs/cgroup:/sys/fs/cgroup
#    - /usr/bin/docker:/usr/bin/docker
#    - /var/run/docker.sock:/var/run/docker.sock
#  command: ./bin/mesos-slave.sh --master=master:5050 --containerizers=docker --attributes=docker:true --resources=ports(*):[20000-32000] --executor_registration_timeout=10mins --no-systemd_enable_support --launcher=posix
#  privileged: true
#  cpu_shares: 256
#  mem_limit: 1G
openlavamaster:
  build: .
  expose:
   - 6322/udp
   - 6322/tcp
   - 6323
   - 6324
   - 6325
  ports:
   - 9876:9876
  links:
   - master:master
  working_dir: /tmp/
  command: python mesoslava/framework.py
  cpu_shares: 128
  mem_limit: 512M

